export const postTypes = {
    FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
    FETCH_POST_REQUEST: "FETCH_POST_REQUEST",
    FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
    FETCH_POST_FAILURE: "FETCH_POST_FAILURE"
}
export const authTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
}
  